### ISSUE TITLE
任务完成状况读取错误？

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/plugin-quest#12]
![image](https://cloud.githubusercontent.com/assets/1596656/11285507/6425aec2-8ed5-11e5-8721-1a5b7eadcdfa.png)

今天在做新飞机系列任务的时候遇到了这个情况。这个任务我还没开呢，但是出现在了“可执行”里面。
稍微调查了一下，发现是这个任务要求月常“海上护卫强化月间”作为前置，但这个月常我这个月还没完成呢(｡•ˇ‸ˇ•｡) 
然后在我把任务切换到第三页，让任务插件了解我现在可以执行“海上护卫强化月间”（也即没有完成）之后这个任务就被归类到“未开放”里去了。
但是，为什么任务插件会奇怪地提前认为我可执行这个任务呢？

**Comment by ruiii** [comment]
之前代码里做了个判断，<del> 是把非单次的任务归为可执行（大概 </del>   仔细看了下是归为已完成
在想要不要改了 一开始全初始化为未开放
读到任务list之后再做判断

一开始打开游戏的话任务都是在已完成里的

那么问题来了 这种情况发生的时候机种转换的type修正了吗？
我记得之前发过一个type为一次任务，后来改成月常的。

**Comment by ruiii** [comment]
这个有再出现过吗。。别的任务？
没有的话先关了？

**Comment by dkwingsmt** [comment]
这个不是（按你说的）事先把所有任务归为“已完成”而不是“未完成”导致的么？

**Comment by Ayaphis** [comment]
这需要调整算法吧，另外彻底解决需要任务完成情况的持久化？

**Comment by dkwingsmt** [comment]
不完全需要那么麻烦，但是我觉得如果一个任务不知道信息的话默认归为“未完成”会更好一点。

**Comment by Ayaphis** [comment]
只有未开放，可执行，已完成3类，你扔未开放的话。。。

**Comment by dkwingsmt** [comment]
感觉没有啥问题？……

**Comment by Ayaphis** [comment]
总觉得会有人反向报BUG

**Comment by dkwingsmt** [comment]
主要是归为可执行的话然后游戏里的任务列表里面又找不到会让人觉得比较慌乱……归为未开放的话，如果从任务列表里面读取到了的话可以不管前置任务手动加入“未完成”列表。

**Comment by KagamiChan** [comment]
related #27
