### ISSUE TITLE
任务“新航空战队编成”条件出错

### ISSUE THREAD

**Issue by dkwingsmt** [poooi/plugin-quest#13]
![image](https://cloud.githubusercontent.com/assets/1596656/11549932/3debff3a-9930-11e5-970b-c33f785a4d85.png)

因为任务插件好像在做 i18n 的大改动，所以我暂时不修改

**Comment by ruiii** [comment]
这个今天下午谈过
现在是需要任务信息的i18n 顺便查错 这样
工作量很大啊。

**Comment by dkwingsmt** [comment]
关于任务信息的查错的事，慢慢来好了。本来错误就不多，一个一个汇报好了【

**Comment by ruiii** [comment]
恩 昨天dkk说的重新处理任务分类 具体是怎么操作？

**Comment by dkwingsmt** [comment]
����tg����������8������������

**Comment by Astra-RX** [comment]
![image](https://cloud.githubusercontent.com/assets/1183568/11759534/f4d93572-a0b6-11e5-83c7-a3ca8011f4af.png)

**Comment by taroxd** [comment]
fixed

**Comment by dkwingsmt** [comment]
fixed 你把 commit 号标出来啊【

**Comment by taroxd** [comment]
不都被你完全重写一遍了么……又不是单独改的

**Comment by dkwingsmt** [comment]
我照着原来的抄的啊……不过好像是后来你提出来了应该是“2dd”【【

**Comment by Ayaphis** [comment]
https://github.com/poooi/plugin-quest/commit/75c7298e4571f5b0fd7e8f93567cf1a1e7c573bb
