### ISSUE TITLE
一直提示加载失败，兼容性问题

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-quest#19]
Electron v0.35.4 x64
Win 10 Pro x64
poi's version: [Commit](https://github.com/poooi/poi/commit/0ad2e79d0e2bdc41b46312ddc2cffbdd045a516e)

如题，一直提示错误。
尝试了删除，重新安装，然后就卡 Installing.
看了一下插件目录，文件倒是下载下来了，但是好像并没有什么卵用？

**Comment by ruiii** [comment]
插件版本呢？

**Comment by wafer-li** [comment]
:joy:  2.0.0-beta.0

**Comment by ruiii** [comment]
诶。。麻烦看下插件目录里有没有node_modules文件夹

**Comment by wafer-li** [comment]
有的，里面有且仅有 `i18n` `pluralize` `sprintf-js` `underscore` 这四个文件夹

**Comment by ruiii** [comment]
诶。。？
麻烦到poi/views/app.cjsx 的248行以前 加上一句 process.env.DEBUG = 1
然后重启 看看开发者工具有没有打印出错误提示

**Comment by wafer-li** [comment]
![qq 20151219001956](https://cloud.githubusercontent.com/assets/12459199/11899994/43d9f47a-a5e6-11e5-858e-c75cf69fc46b.png)

:joy:  好像并没有什么不妥？
不对，一共弹了3 个，两个是上面那个样子的，另一个有一个比较长的 warning.
I will use gist to display it.

**Comment by wafer-li** [comment]
https://gist.github.com/Wafer-Li/05b9ddd8c6e3eb81ec61

**Comment by ruiii** [comment]
喔。。缺少了个module。。到插件文件夹里执行一次npm i 应该可以了

**Comment by wafer-li** [comment]
OK.

**Comment by wafer-li** [comment]
Fixed.
I wonder if it is my problem?

**Comment by ruiii** [comment]
刚才找问题的时候请两位组里的dalao试了一下
一位安卓正常 另一位也出现了缺少 `underscore.inflection` 的问题
不清楚具体原因 总之先观察观察

**Comment by wafer-li** [comment]
:joy: 

2.2.0 之后继续出现此问题，跑到 插件目录下跑了一遍 `npm i`
https://gist.github.com/Wafer-Li/736b441160c4e28a3f00

希望能有帮助。

**Comment by ruiii** [comment]
git版更换了模组，麻烦试试新模组能不能正常安装（

**Comment by dkwingsmt** [comment]
你得推个新版本到 npm 把 0 0

**Comment by ruiii** [comment]
~~欧 也好~~
发了个beta版

**Comment by wafer-li** [comment]
(应该是) 新的 beta 版 `version 2.0.3-beta` 成功安装，没问题了。
