### ISSUE TITLE
关于增加分类和显示任务完成情况

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-quest#2]
1、希望增加【日常】【周常】【月常】三个分类

2、将结婚系列任务【WB系列】单独独立出一个分类

3、希望类似 KCV 一样能够显示 当天/周/月 剩下的未完成的任务
      （可以通过在上述新增分类下显示任务的完成情况来实现）

**Comment by malichan** [comment]
1 和 2 － 下个版本加进来
3 － 感觉可以实现，但有点麻烦。只有用户把任务列表的每一页都翻过一遍之后，程序才能拿到完整的任务列表，进而知道哪些任务还没做。这样感觉不是特别优雅，但是好像也没什么别的好办法。

**Comment by malichan** [comment]
See the latest release v1.1.0
