### ISSUE TITLE
“远征信息”插件远征38条件验证有误

### ISSUE THREAD

**Issue by yukixz** [poooi/plugin-quest#28]
> 远征38（东急2）成功条件是有4条以上各自携带2个以上桶，而插件似乎只验证总桶数>8...事实上例如三条三桶+一条一桶的配置远征仍然会失败（派出时poi会提示失败，估计api能收到失败信息？），但插件上显示配置可行的绿点。
> 望予修正，多谢。
> 另，远征24的大成功条件已经确证为至少4桶4闪，望能加入文字部分说明。

by @Yogomove at https://github.com/poooi/poi/issues/973

**Comment by ruiii** [comment]
刚才在日文 wiki 上查看 24 远征的条件 没有写确证 4 桶 4 闪
请问是在哪看到的呢？

**Comment by Yogomove** [comment]
发错区抱歉orz
4桶4闪的情报日文wikiwiki那边的话在远征页顶部"「北方航路海上護衛」「水上機前線輸送」について、大成功には何が作用しているのか"的折叠里面...wikia那边有个检证帖不过一下找不到了orz

**Comment by Yogomove** [comment]
顺带一提，ID为8xx的任务维持日文是特意如此还是尚未翻译...

**Comment by Ayaphis** [comment]
@Yogomove 是不是有展示任务ID，展示任务ID，就是相关的中文翻译数据没有更新（https://github.com/poooi/plugin-quest/blob/master/index.cjsx#L84
