### ISSUE TITLE
已经完成了的任务出现在了“可执行”分类

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-quest#3]
版本：electron-v0.28.3-ia32  
           the latest master branch of poi
           quest-info v1.1.1

仅出现在周常和月常任务中

**Comment by wafer-li** [comment]
![qq 20150627213023](https://cloud.githubusercontent.com/assets/12459199/8391976/c278306e-1d13-11e5-9fe6-5bacc7d513e7.png)

Bw02我早已完成了，不然也不会出现Bw08能够执行的情况
（根据任务的流程树，只有Bw02的进阶任务Bw05完成后，才能开启东方系列周常）

**Comment by malichan** [comment]
看起来是一个bug，不过提供的信息太少我没法解决
你能详细说下你从打开poi开始的任务相关操作吗？比如打开poi的时候i号任务有没有完成，之后又依次接受了或完成了哪些任务……

**Comment by wafer-li** [comment]
@malichan 
好的，首先，我的i号已经完成了，但是日常打3个补给船的任务没有完成
这种状态下，我打开poi，刷新了一遍任务列表，然后，把日常的3补给完成了
此时就出现了上图的情况

**Comment by wafer-li** [comment]
同时，也因为我完成了这周的ro号任务，月常任务列表的可执行分类也出现了我早已完成的「水雷戦隊」南西へ！

**Comment by malichan** [comment]
啊 我知道哪里错了  感谢反馈！
