### ISSUE TITLE
关于月常水上打击部队的误解

### ISSUE THREAD

**Issue by wafer-li** [poooi/plugin-quest#30]
任务 A43 + 后续任务 Bm04 的完成条件错误。
此任务链的要求应为 **限制舰型**，而非低速即可。

http://bbs.nga.cn/read.php?tid=9781134

**Comment by dkwingsmt** [comment]
了解，有空去改【

**Comment by wafer-li** [comment]
:joy: 之前考虑到 i18n 问题才提的 issue，原来改这个根本不用写翻译啊……

**Comment by dkwingsmt** [comment]
对，不用写翻译，要改麻烦得多的地方……
