### ISSUE TITLE
[BUG]任务统计数值不正确

### ISSUE THREAD

**Issue by Lanyangzhi** [poooi/plugin-quest#59]
あ号作战未完成 显示为已完成
重新接取任务仍显示已完成
![image](https://user-images.githubusercontent.com/10362972/65831898-b9dfef80-e2f0-11e9-95a0-01ac6d147251.png)

**Comment by KagamiChan** [comment]
API 只会返回完成度百分比。因为 あ号 是一个复合计数的任务，数值不对的时候无法根据 API 的数据来进行校准

あ号 在活动期间也很容易不准确，参考 poooi/poi#1450
